resources:
- bases/linstor-operator.clusterserviceversion.yaml
- ./operator
- ../../piraeus-operator/config/samples
- ../../piraeus-operator/config/scorecard
- ../../config/monitoring

patches:
- target:
    kind: ClusterServiceVersion
  path: csv-resource-patch.yaml

replacements:
- source:
    fieldPath: metadata.name
    kind: ConfigMap
    name: image-config
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=manager].env.[name=IMAGE_CONFIG_MAP_NAME].value
    select:
      kind: Deployment
      name: controller-manager

configMapGenerator:
  # Replace the sig-storage sidecars with RedHat builds
  - name: linstor-operator-image-config
    namespace: linbit-sds
    files:
    - 0_sig_storage_images.yaml
    - 0_redhat_ose_images.yaml
    behavior: merge
    options:
      disableNameSuffixHash: true
