stages:
  - prepare
  - build
  - build_olm
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LINSTOR_KUBERNETES_TESTS_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.at.linbit.com/kubernetes/linstor-kubernetes-tests.git
  PROVISIONER_IMAGE: $CI_REGISTRY/kubernetes/linstor-kubernetes-tests/virter-kubeadm-playbook:latest
  TEST_SUITE_IMAGE: $CI_REGISTRY/kubernetes/linstor-kubernetes-tests/linstor-kubernetes-tests:latest
  VIRTER_VERSION: v0.13.1
  VMSHED_VERSION: v0.12.0
  # Upstream uses a newer version. This is fine, as we only use this version for building the CSV.
  # Newer versions do not support "operator-sdk generate csv"
  OPERATOR_SDK_VERSION: v0.18.0
  OPM_VERSION: v1.15.3
  HELM_VERSION: v3.4.1
  CRANE_VERSION: v0.2.1
  YQ_VERSION: 3.3.4
  JQ_VERSION: "1.6"

prepare-version:
  image: python:3
  stage: prepare
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  variables:
    # git describe needs full history access
    GIT_DEPTH: 0
    # git describe does not need the submodule
    GIT_SUBMODULE_STRATEGY: none
  script:
    - SEMVER=$(hack/getsemver.py)
    - echo "SEMVER=${SEMVER}" >> .ci-build.env
    - echo "TAG=v${SEMVER/+/-}" >> .ci-build.env
  artifacts:
    reports:
      dotenv: .ci-build.env

prepare-bins:
  image: ${BUILD_HELPER_IMAGE}
  stage: prepare
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - . /usr/local/bin/gitlab-utils.sh
    - ci_prepare_tools
    - ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
    - ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    - ci_fetch_binary operator-sdk operator-sdk-$OPERATOR_SDK_VERSION https://github.com/operator-framework/operator-sdk/releases/download/$OPERATOR_SDK_VERSION/operator-sdk-$OPERATOR_SDK_VERSION-x86_64-linux-gnu
    - ci_fetch_binary opm opm-${OPM_VERSION} https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm
    - ci_fetch_binary yq yq-$YQ_VERSION https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64
    - ci_fetch_binary jq jq-$JQ_VERSION https://github.com/stedolan/jq/releases/download/jq-$JQ_VERSION/jq-linux64
    - ci_fetch_tar helm-$HELM_VERSION https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -z
    - ci_fetch_tar crane-$CRANE_VERSION https://github.com/google/go-containerregistry/releases/download/$CRANE_VERSION/go-containerregistry_Linux_x86_64.tar.gz -z
  artifacts:
    paths:
      - bin
      - download

prepare-tools:
  tags:
    - docker
    - amd64
  stage: prepare
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      allow_failure: true
  script:
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - docker build -f .gitlab/Dockerfile.operator-sdk-tools -t $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest .gitlab
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest

build_chart:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build
  script:
    - export "PATH=$PWD/bin:$PATH"
    - make chart SEMVER=$SEMVER
    - curl --fail --user $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file out/helm/linstor-$SEMVER.tgz $LINBIT_REGISTRY_HELM/
  tags:
    - shell

build_operator:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build
  script:
    - export "PATH=$PWD/bin:$PATH"
    - if [ -n "$CI_COMMIT_TAG" ]; then NOCACHE=true ; else NOCACHE=false ; fi
    - TARGET=$LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator:$TAG
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - make linstor-operator
    - docker buildx build --pull --push --platform $PUBLISH_PLATFORMS -t $TARGET linstor-operator --no-cache=$NOCACHE
    - echo "OPERATOR_IMAGE=$LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator:$TAG" > .build.env
  artifacts:
    reports:
      dotenv:
        - .build.env
  tags:
    - multiarch

build_olm:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build_olm
  script:
    - export "PATH=$PWD/bin:$PATH"
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - make olm SEMVER=$SEMVER OLM_REGISTRY=$LINBIT_DOCKER_REGISTRY/linstor-operator-test
    - docker build -t $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG out/olm-bundle/$SEMVER/
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG
    - opm index add --permissive --mode semver --build-tool docker --from-index $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest --bundles $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG --tag $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest --bundles $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG --tag $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest
  tags:
    - docker

deploy_olm:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: test
  image: $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest
  script:
    - operator-sdk bundle validate --verbose --image-builder none $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG
  dependencies:
    # Explicitly: do not depend on prepare-bins, we want out own version of operator-sdk
    - build_olm
    - prepare-version

test:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: test
  tags:
    - libvirt
  cache:
    paths:
      - download
  before_script:
    - mkdir -p tests/linstor-kubernetes-tests
    - git clone --depth=1 $LINSTOR_KUBERNETES_TESTS_REPO tests/linstor-kubernetes-tests
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export "PATH=$PWD/bin:$PATH"
    - docker image pull $PROVISIONER_IMAGE
    - docker image pull $TEST_SUITE_IMAGE
    - HELM_VALUES_BASE64=$(yq write test-helm-config.yaml operator.image $OPERATOR_IMAGE | base64 --wrap=0 -)
    - cd tests/linstor-kubernetes-tests
    - virter image pull centos-7-k8s-1-21 $LINBIT_DOCKER_REGISTRY/linstor-kubernetes-tests/base:centos-7-k8s-1-21
    - >-
      make run
      PROVISIONER_IMAGE=$PROVISIONER_IMAGE
      TEST_SUITE_IMAGE=$TEST_SUITE_IMAGE
      VMSHED_EXTRA_ARGS="
      --set values.HelmRepo=$LINBIT_REGISTRY_HELM
      --set values.HelmChartVersion=$SEMVER
      --set values.HelmValuesBase64=$HELM_VALUES_BASE64
      "
  artifacts:
    # provide a convenient name so that the downloaded artifacts can be identified
    name: $CI_PROJECT_NAME-$CI_JOB_ID
    paths:
      - tests/linstor-kubernetes-tests/tests-out/
    when: always
    reports:
      junit: tests/linstor-kubernetes-tests/tests-out/test-results/*.xml

container_scanning:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_TAG
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    # No need to clone the repo, we exclusively work on artifacts.  See
    # https://docs.gitlab.com/ee/ci/runners/README.html#git-strategy
    GIT_STRATEGY: none
  script:
    - trivy --version
    - trivy client --exit-code 0 --format template --template "@/contrib/html.tpl" -o container-scan.html "$OPERATOR_IMAGE"
    # Prints full report
    - trivy client --exit-code 0 "$OPERATOR_IMAGE"
    # Fail on critical (unfixed) vulnerabilities
    - trivy client --exit-code 1 --ignore-unfixed --severity CRITICAL "$OPERATOR_IMAGE"
  # Ideally, we would use container_scanning for the artifact here. That is currently a paid feature, so we have to use code quality
  artifacts:
    when: always
    expose_as: "Container Scan"
    paths:
      - container-scan.html


publish-image:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p $HOME/.docker
    - ln -snf $DOCKER_PUBLISH_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - for PLATFORM in $(echo $PUBLISH_PLATFORMS | tr ',' '\n') ; do
    -   ARCH=${PLATFORM#*/}
    -   crane copy --platform $PLATFORM $OPERATOR_IMAGE $PUBLISH_REGISTRY/$ARCH/linstor-operator:$TAG
    -   crane tag $PUBLISH_REGISTRY/$ARCH/linstor-operator:$TAG latest
    - done



publish-chart:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  script:
    - export "PATH=$PWD/bin:$PATH"
    - eval $(ssh-agent -s)
    - trap 'ssh-agent -k' EXIT
    - cat $GITHUB_DEPLOY_KEY | ssh-add -
    - export GIT_AUTHOR_NAME="LinbitPRBot"
    - export GIT_COMMITTER_NAME="LinbitPRBot"
    - export GIT_AUTHOR_EMAIL="linbitprbot@users.noreply.github.com"
    - export GIT_COMMITTER_EMAIL="linbitprbot@users.noreply.github.com"
    - make publish SEMVER=$SEMVER UPSTREAMGIT=git@github.com:LINBIT/linstor-operator-builder.git
  tags:
    - shell

publish-csv:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  dependencies:
    - prepare-version
  tags:
    - docker
  script:
    - export "PATH=$PWD/bin:$PATH"
    - ln -snf $DOCKER_AUTH_CONFIG_FILE $HOME/.docker/config.json
    - docker login -u unused -p $SCAN_TOKEN_OPERATOR scan.connect.redhat.com
    - make upload REGISTRY=scan.connect.redhat.com/$SCAN_REGISTRY_OPERATOR_PID TAG=$TAG DOCKER_BUILD_ARGS="--pull --no-cache" PUSH_LATEST=no
    - docker logout scan.connect.redhat.com
    # TODO: we should wait on the operator image to be certified here
    # TODO: upload the olm-bundle for scanning!
