stages:
  - sync
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CHART_VERSION: 0.0.0-r$CI_COMMIT_SHA
  OPERATOR_VERSION: $CI_COMMIT_SHA

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

# Repo sync runs on a schedule
# https://gitlab.linbit/help/ci/pipelines/schedules
upstream-sync:
  extends: .go-cache
  image: golang:1.14
  stage: sync
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - cd .gitlab/syncer
    - go run sync.go


build_chart:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_PIPELINE_SOURCE != 'schedule'
  stage: build
  cache:
    paths:
      - bin
  script:
    - mkdir -p bin
    - "[ -e bin/helm ] || curl -L https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz | tar zx --directory=bin --strip=1 linux-amd64/helm"
    - "[ -e bin/yq ] || { curl -L https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 > bin/yq && chmod +x bin/yq ; }"
    - export PATH="$(readlink -f bin):$PATH"
    - make chart CHART_VERSION=$CHART_VERSION
    - curl --user $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file out/helm/linstor-$CHART_VERSION.tgz $LINBIT_REGISTRY_HELM/
  tags:
    - shell

build_operator:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_PIPELINE_SOURCE != 'schedule'
  stage: build
  script:
    # use special OPERATOR_REGISTRY until https for LINBIT Nexus Repository is fixed
    - docker login -u $OPERATOR_REGISTRY_USER -p $OPERATOR_REGISTRY_PASSWORD $OPERATOR_REGISTRY
    - make operator REGISTRY=$OPERATOR_REGISTRY TAG=$OPERATOR_VERSION
    - make upload REGISTRY=$OPERATOR_REGISTRY TAG=$OPERATOR_VERSION
  tags:
    - shell

test:
  rules:
    - if: $CI_MERGE_REQUEST_ID
  stage: test
  variables:
    CHART_REGISTRY: $LINBIT_REGISTRY_HELM
    OPERATOR_IMAGE: $OPERATOR_REGISTRY/linstor-operator:$OPERATOR_VERSION
  trigger:
    project: kubernetes/linstor-kubernetes-tests
    strategy: depend
