stages:
  - prepare
  - build
  - build_olm
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LINSTOR_KUBERNETES_TESTS_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.at.linbit.com/kubernetes/linstor-kubernetes-tests.git
  PROVISIONER_IMAGE: $CI_REGISTRY/kubernetes/linstor-kubernetes-tests/virter-kubeadm-playbook:latest
  TEST_SUITE_IMAGE: $CI_REGISTRY/kubernetes/linstor-kubernetes-tests/linstor-kubernetes-tests:latest
  VIRTER_VERSION: v0.5.0
  VMSHED_VERSION: v0.5.0
  # Upstream uses a newer version. This is fine, as we only use this version for building the CSV.
  # Newer versions do not support "operator-sdk generate csv"
  OPERATOR_SDK_VERSION: v0.18.0
  OPM_VERSION: v1.15.3
  HELM_VERSION: v3.4.1
  CRANE_VERSION: v0.2.1
  YQ_VERSION: 3.3.4
  JQ_VERSION: "1.6"

prepare-version:
  image: python:3
  stage: prepare
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  variables:
    # git describe needs full history access
    GIT_DEPTH: 0
    # git describe does not need the submodule
    GIT_SUBMODULE_STRATEGY: none
  script:
    - SEMVER=$(hack/getsemver.py)
    - echo "SEMVER=${SEMVER}" >> .ci-build.env
    - echo "TAG=v${SEMVER/+/-}" >> .ci-build.env
  artifacts:
    reports:
      dotenv: .ci-build.env

prepare-bins:
  image: ${BUILD_HELPER_IMAGE}
  stage: prepare
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - . /usr/local/bin/gitlab-utils.sh
    - ci_prepare_tools
    - ci_fetch_binary virter virter-$VIRTER_VERSION https://github.com/LINBIT/virter/releases/download/$VIRTER_VERSION/virter-linux-amd64
    - ci_fetch_binary vmshed vmshed-$VMSHED_VERSION https://github.com/LINBIT/vmshed/releases/download/$VMSHED_VERSION/vmshed-linux-amd64
    - ci_fetch_binary operator-sdk operator-sdk-$OPERATOR_SDK_VERSION https://github.com/operator-framework/operator-sdk/releases/download/$OPERATOR_SDK_VERSION/operator-sdk-$OPERATOR_SDK_VERSION-x86_64-linux-gnu
    - ci_fetch_binary opm opm-${OPM_VERSION} https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm
    - ci_fetch_binary yq yq-$YQ_VERSION https://github.com/mikefarah/yq/releases/download/$YQ_VERSION/yq_linux_amd64
    - ci_fetch_binary jq jq-$JQ_VERSION https://github.com/stedolan/jq/releases/download/jq-$JQ_VERSION/jq-linux64
    - ci_fetch_tar helm-$HELM_VERSION https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -z
    - ci_fetch_tar crane-$CRANE_VERSION https://github.com/google/go-containerregistry/releases/download/$CRANE_VERSION/go-containerregistry_Linux_x86_64.tar.gz -z
    - echo "PATH=\$CI_PROJECT_DIR/bin/:$PATH" > .bins.env
  artifacts:
    paths:
      - bin
      - download
    reports:
      dotenv: .bins.env

prepare-tools:
  tags:
    - docker
    - amd64
  stage: prepare
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == 'master'
      when: manual
      allow_failure: true
  script:
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - docker build -f .gitlab/Dockerfile.operator-sdk-tools -t $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest .gitlab
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest

build_chart:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build
  script:
    - make chart SEMVER=$SEMVER
    - curl --fail --user $LINBIT_REGISTRY_USER:$LINBIT_REGISTRY_PASSWORD --upload-file out/helm/linstor-$SEMVER.tgz $LINBIT_REGISTRY_HELM/
  tags:
    - shell

build_operator:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build
  script:
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - make operator REGISTRY=$LINBIT_DOCKER_REGISTRY/linstor-operator-test TAG=$TAG
    - make upload REGISTRY=$LINBIT_DOCKER_REGISTRY/linstor-operator-test TAG=$TAG
    - if [ "$CI_COMMIT_BRANCH" == 'master' ] ; then
    -   make upload REGISTRY=$LINBIT_DOCKER_REGISTRY/linstor-operator-test TAG=latest
    - fi
  tags:
    - shell

build_olm:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: build_olm
  script:
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - make olm SEMVER=$SEMVER OLM_REGISTRY=$LINBIT_DOCKER_REGISTRY/linstor-operator-test
    - docker build -t $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG out/olm-bundle/$SEMVER/
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG
    - opm index add --mode semver --build-tool docker --from-index $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest --bundles $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG --tag $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest --bundles $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG --tag $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest
    - docker push $LINBIT_DOCKER_REGISTRY/linstor-operator-test/catalog:latest
  tags:
    - docker

deploy_olm:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: test
  image: $LINBIT_DOCKER_REGISTRY/linstor-operator-test/operator-sdk:latest
  script:
    - operator-sdk bundle validate --verbose --image-builder none $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator-bundle:$TAG
  dependencies:
    # Explicitly: do not depend on prepare-bins, we want out own version of operator-sdk
    - build_olm
    - prepare-version

test:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'master'
  stage: test
  tags:
    - libvirt
  cache:
    paths:
      - download
  before_script:
    - mkdir -p tests/linstor-kubernetes-tests
    - git clone --depth=1 $LINSTOR_KUBERNETES_TESTS_REPO tests/linstor-kubernetes-tests
    - docker login -u $LINBIT_REGISTRY_USER -p $LINBIT_REGISTRY_PASSWORD $LINBIT_DOCKER_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image pull $PROVISIONER_IMAGE
    - docker image pull $TEST_SUITE_IMAGE
    - HELM_VALUES_BASE64=$(yq write test-helm-config.yaml operator.image $LINBIT_DOCKER_REGISTRY/linstor-operator-test/linstor-operator:$TAG | base64 --wrap=0 -)
    - cd tests/linstor-kubernetes-tests
    - virter image pull centos-7-k8s-1-18 -u ${TEST_VM_BASE_IMAGE} 2> /dev/null || echo "image exists"
    - >-
      make run
      PROVISIONER_IMAGE=$PROVISIONER_IMAGE
      TEST_SUITE_IMAGE=$TEST_SUITE_IMAGE
      VMSHED_EXTRA_ARGS="
      --set values.HelmRepo=$LINBIT_REGISTRY_HELM
      --set values.HelmChartVersion=$SEMVER
      --set values.HelmValuesBase64=$HELM_VALUES_BASE64
      "
  artifacts:
    # provide a convenient name so that the downloaded artifacts can be identified
    name: $CI_PROJECT_NAME-$CI_JOB_ID
    paths:
      - tests/linstor-kubernetes-tests/tests-out/
    when: always
    reports:
      junit: tests/linstor-kubernetes-tests/tests-out/test-results/*.xml

.push-image:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  script:
    - docker login -u $DEPLOY_REGISTRY_USER -p $DEPLOY_REGISTRY_PASSWORD $DEPLOY_REGISTRY
    - make operator ARCH=$ARCH TAG=$TAG
    - make upload ARCH=$ARCH TAG=$TAG

push-amd64:
  extends: .push-image
  variables:
    ARCH: amd64
  tags:
    - amd64
    - docker

push-s390x:
  extends: .push-image
  variables:
    ARCH: s390x
  tags:
    - s390x

publish-chart:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  script:
    - eval $(ssh-agent -s)
    - trap 'ssh-agent -k' EXIT
    - cat $GITHUB_DEPLOY_KEY | ssh-add -
    - export GIT_AUTHOR_NAME="LinbitPRBot"
    - export GIT_COMMITTER_NAME="LinbitPRBot"
    - export GIT_AUTHOR_EMAIL="linbitprbot@users.noreply.github.com"
    - export GIT_COMMITTER_EMAIL="linbitprbot@users.noreply.github.com"
    - make publish SEMVER=$SEMVER UPSTREAMGIT=git@github.com:LINBIT/linstor-operator-builder.git
  tags:
    - shell

publish-csv:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
  dependencies:
    - prepare-version
  tags:
    - docker
  script:
    - docker login -u unused -p $SCAN_TOKEN_OPERATOR scan.connect.redhat.com
    - make upload REGISTRY=scan.connect.redhat.com/$SCAN_REGISTRY_OPERATOR_PID TAG=$TAG DOCKER_BUILD_ARGS="--pull --no-cache" PUSH_LATEST=no
    - docker logout scan.connect.redhat.com
    # TODO: we should wait on the operator image to be certified here
    # TODO: upload the olm-bundle for scanning!
