operator:
  controller:
    controllerImage: drbd.io/linstor-controller:v1.16.0-rc.2
  satelliteSet:
    satelliteImage: drbd.io/linstor-satellite:v1.16.0-rc.2
    storagePools:
      lvmThinPools:
      - name: thinpool
        volumeGroup: linstor_thinpool
        thinVolume: thinpool
        devicePaths:
        - /dev/vdb
