etcd:
  persistentVolume:
    enabled: false

operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: thinpool
        volumeGroup: linstor_thinpool
        thinVolume: thinpool
        devicePaths:
        - /dev/vdb

csi-snapshotter:
  enabled: false
