etcd:
  persistentVolume:
    enabled: false

operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: sda
        volumeGroup: linstor_sda
        thinVolume: sda
        devicePaths:
        - /dev/sda
