---
# Source: linstor/templates/ha-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linstor-ha-controller
  namespace: MY-HA-CTRL-NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linstor-ha-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linstor-ha-controller
    spec:
      serviceAccountName: ha-controller
      initContainers:
        - name: wait-for-api
          image: drbd.io/linstor-k8s-ha-controller:v0.3.0
          imagePullPolicy: "IfNotPresent"
          command:
            - /linstor-wait-until
            - api-online
          env:
            - name: LS_CONTROLLERS
              value: MY-LINSTOR-URL
      containers:
        - name: controller
          image: drbd.io/linstor-k8s-ha-controller:v0.3.0
          imagePullPolicy: "IfNotPresent"
          args:
            - --leader-election=true
            - --leader-election-lease-name=$(NAME)
            - --leader-election-namespace=$(NAMESPACE)
            - --v=5
          env:
            - name: LS_CONTROLLERS
              value: MY-LINSTOR-URL
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
      imagePullSecrets:
        - name: "drbdiocred"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: linstor-ha-controller
      securityContext:
---
# Source: linstor/templates/ha-controller-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ha-controller
  namespace: MY-HA-CTRL-NAMESPACE
---
# Source: linstor/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ha-controller
rules:
  - verbs:
      - list
      - watch
      - delete
    apiGroups:
      - ""
    resources:
      - pods
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - watch
---
# Source: linstor/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ha-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: MY-HA-CTRL-NAMESPACE
---
# Source: linstor/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ha-controller
  namespace: MY-HA-CTRL-NAMESPACE
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
# Source: linstor/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ha-controller
  namespace: MY-HA-CTRL-NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: MY-HA-CTRL-NAMESPACE
