apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |
      [
        {
          "apiVersion": "linstor.linbit.com/v1",
          "kind": "LinstorController",
          "metadata": {
            "name": "linstor"
          },
          "spec": {
            "controllerImage": "",
            "dbConnectionURL": "k8s",
            "drbdRepoCred": "",
            "priorityClassName": ""
          },
          "status": {
            "errors": []
          }
        },
        {
          "apiVersion": "linstor.linbit.com/v1",
          "kind": "LinstorCSIDriver",
          "metadata": {
            "name": "linstor"
          },
          "spec": {
            "controllerReplicas": 1,
            "controllerEndpoint": "http://linstor:3370",
            "csiControllerServiceAccountName": "csi-controller",
            "csiNodeServiceAccountName": "csi-node",
            "linstorPluginImage": "",
            "imagePullSecret": ""
          },
          "status": {
            "errors": []
          }
        },
        {
          "apiVersion": "linstor.linbit.com/v1",
          "kind": "LinstorSatelliteSet",
          "metadata": {
            "name": "linstor-satellites"
          },
          "spec": {
            "automaticStorageType": "None",
            "controllerEndpoint": "http://linstor:3370",
            "drbdRepoCred": "",
            "kernelModuleInjectionMode": "ShippedModules",
            "priorityClassName": "",
            "satelliteImage": ""
          },
          "status": {
            "errors": []
          }
        }
      ]
    categories: "Storage"
    description: LINSTOR Kubernetes Operator
    support: LINBIT
    certified: "true"
    capabilities: Seamless Upgrades
    repository: https://github.com/piraeusdatastore/piraeus-operator
spec:
  customresourcedefinitions:
    owned:
      - description: LinstorController is the Schema for the linstorcontrollersets
          API
        kind: LinstorController
        name: linstorcontrollers.linstor.linbit.com
        version: v1
        resources:
          - kind: Service
            name: ''
            version: v1
          - kind: Deployment
            name: ''
            version: v1
          - kind: ConfigMap
            name: ''
            version: v1
          - kind: Pod
            name: ''
            version: v1
        specDescriptors:
          - path: controllerImage
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: dbConnectionURL
            description: DBConnectionURL is the URL of the database endpoint for LINSTOR Controller
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:label'
          - path: drbdRepoCred
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: priorityClassName
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: serviceAccountName
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
        statusDescriptors:
          - path: errors
            displayName: Errors
            description: Errors encountered during operations
            x-descriptors:
              - 'urn:alm:descriptor:text'
      - description: LinstorSatelliteSet is the Schema for the linstornodesets API
        kind: LinstorSatelliteSet
        name: linstorsatellitesets.linstor.linbit.com
        version: v1
        resources:
          - kind: DaemonSet
            name: ''
            version: v1
          - kind: ConfigMap
            name: ''
            version: v1
          - kind: Pod
            name: ''
            version: v1
        specDescriptors:
          - path: automaticStorageType
            displayName: Automatic Storage Type
            description: If set, the operator will automatically create storage
              pools of the specified type for all devices that can be found. The
              name of the storage pools matches the device name. For example, all
              devices `/dev/sdc` will be part of the `sdc` storage pool.
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:select:None'
              - 'urn:alm:descriptor:com.tectonic.ui:select:LVM'
              - 'urn:alm:descriptor:com.tectonic.ui:select:LVMTHIN'
              - 'urn:alm:descriptor:com.tectonic.ui:select:ZFS'
          - path: controllerEndpoint
            displayName: LINSTOR Controller Endpoint
            description: In-Cluster URL of the LINSTOR Controller
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:label'
          - path: drbdRepoCred
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: kernelModuleInjectionMode
            displayName: Kernel Module Injection Mode
            description: Determine how required kernel modules should be loaded
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:select:None'
              - 'urn:alm:descriptor:com.tectonic.ui:select:Compile'
              - 'urn:alm:descriptor:com.tectonic.ui:select:ShippedModules'
              - 'urn:alm:descriptor:com.tectonic.ui:select:DepsOnly'
          - path: priorityClassName
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: satelliteImage
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
        statusDescriptors:
          - path: errors
            displayName: Errors
            description: Errors encountered during operations
            x-descriptors:
              - 'urn:alm:descriptor:text'
      - description: LinstorCSIDriver is the Schema for the linstorcsidrivers API
        kind: LinstorCSIDriver
        name: linstorcsidrivers.linstor.linbit.com
        version: v1
        resources:
          - kind: Deployment
            name: ''
            version: v1
          - kind: DaemonSet
            name: ''
            version: v1
          - kind: Pod
            name: ''
            version: v1
        specDescriptors:
          - path: controllerReplicas
            displayName: CSI Controller Replicas
            description: Number of replicas for the CSI controller
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
          - path: controllerEndpoint
            displayName: LINSTOR Controller Endpoint
            description: In-Cluster URL of the LINSTOR Controller
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:label'
          - path: csiControllerServiceAccountName
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: csiNodeServiceAccountName
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: linstorPluginImage
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
          - path: imagePullSecret
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:hidden'
        statusDescriptors:
          - path: errors
            displayName: Errors
            description: Errors encountered during operations
            x-descriptors:
              - 'urn:alm:descriptor:text'
  displayName: Linstor Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIzLjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA1MDAgMzAwIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA1MDAgMzAwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+Cgkuc3Qwe2NsaXAtcGF0aDp1cmwoI1NWR0lEXzJfKTt9Cgkuc3Qxe2NsaXAtcGF0aDp1cmwoI1NWR0lEXzRfKTtmaWxsOiMxRTI5M0E7fQoJLnN0MntjbGlwLXBhdGg6dXJsKCNTVkdJRF80Xyk7ZmlsbDojRjc4RjIyO30KPC9zdHlsZT4KPGcgaWQ9IkFydHdvcmtfMTRfMV8iPgoJPGc+CgkJPGRlZnM+CgkJCTxyZWN0IGlkPSJTVkdJRF8xXyIgeD0iOTQuMDciIHk9IjEwOC45MiIgd2lkdGg9IjMxOC45NiIgaGVpZ2h0PSI0OS42OSIvPgoJCTwvZGVmcz4KCQk8Y2xpcFBhdGggaWQ9IlNWR0lEXzJfIj4KCQkJPHVzZSB4bGluazpocmVmPSIjU1ZHSURfMV8iICBzdHlsZT0ib3ZlcmZsb3c6dmlzaWJsZTsiLz4KCQk8L2NsaXBQYXRoPgoJCTxnIGNsYXNzPSJzdDAiPgoJCQk8ZGVmcz4KCQkJCTxyZWN0IGlkPSJTVkdJRF8zXyIgeD0iOTQuMDciIHk9IjEwOC45MiIgd2lkdGg9IjMxOC45NiIgaGVpZ2h0PSI0OS42OSIvPgoJCQk8L2RlZnM+CgkJCTxjbGlwUGF0aCBpZD0iU1ZHSURfNF8iPgoJCQkJPHVzZSB4bGluazpocmVmPSIjU1ZHSURfM18iICBzdHlsZT0ib3ZlcmZsb3c6dmlzaWJsZTsiLz4KCQkJPC9jbGlwUGF0aD4KCQkJPHBhdGggY2xhc3M9InN0MSIgZD0iTTI2My45MSwxMjguNDhoLTcuNzljLTQuMDgsMC01LjE4LTAuOTctNS4xOC00LjAzdi0xLjY1YzAtMy43NiwyLjEtMy45OCw2LjM2LTMuOTMKCQkJCWMzLjY0LDAsMTMuMTIsMC4yNSwxNy44MywwLjY3VjExMWMtNC43OC0xLjQzLTEyLjU2LTIuMjUtMjEuNjktMi4wNWMtNy45MiwwLjE0LTE0LjA2LDIuOTctMTQuNTMsMTEuNzcKCQkJCWMyLjIxLDIuMTEsMy41OSw1LjE0LDMuNTksNy45OHY3LjI0YzIuMDksMS45OSw1LjM5LDMuNDUsMTAuNTcsMy40NWg3LjU0YzMuNjIsMCw0LjQzLDEuNDMsNC40MywzLjgzdjEuOTMKCQkJCWMwLDIuOTYtMi40OCwzLjU0LTUuNjEsMy41NGMtNi44NCwwLTE1Ljk0LTAuNDctMTguODgtMC43M3Y4LjU0YzYuMzYsMS44MywxMC40MiwyLjExLDIxLjY0LDIuMTFjNy4yOCwwLDE0LjkxLTIuMjYsMTQuOTEtMTMuOTEKCQkJCXYtMi43OEMyNzcuMDksMTM2LjU2LDI3NC43MywxMjguNDgsMjYzLjkxLDEyOC40OCIvPgoJCQk8cG9seWdvbiBjbGFzcz0ic3QxIiBwb2ludHM9IjI3OC45NiwxMTkuMjcgMjkzLjA0LDExOS4yNyAyOTMuMDQsMTU4LjA4IDMwNS4xLDE1OC4wOCAzMDUuMSwxMTkuMjcgMzE5LjYyLDExOS4yNyAzMTkuNjIsMTA5LjM1IAoJCQkJMjc4Ljk2LDEwOS4zNSAJCQkiLz4KCQkJPHBhdGggY2xhc3M9InN0MSIgZD0iTTM0NC43NywxMDkuMDJjLTEyLjM1LDAtMjEuOTMsMi4yLTIxLjkzLDI1LjAzYzAsMjIuMTcsOC43LDI0LjMsMjEuOTMsMjQuM2MxMy4yNCwwLDIxLjg5LTIuOCwyMS44OS0yNC4zCgkJCQlDMzY2LjY2LDExMS4yMiwzNTcuNDksMTA5LjAyLDM0NC43NywxMDkuMDIgTTM0NC43NywxNDguNDNjLTguMzEsMC05Ljg3LTIuNDYtOS44Ny0xNC4zOGMwLTEzLjkxLDIuNTctMTUuMTEsOS44Ny0xNS4xMQoJCQkJYzcuNTIsMCw5LjgzLDEuNjUsOS44MywxNS4xMUMzNTQuNiwxNDUuOTMsMzUyLjM4LDE0OC40MywzNDQuNzcsMTQ4LjQzIi8+CgkJCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik00MDMuMjYsMTM5LjIzYzMuMzMtMS4wNyw4LjI5LTIuNjMsOC4yOS0xNC40OGMwLTExLjg1LTYuNTQtMTUuNC0xNS40Ni0xNS40aC0yMy43N3Y0OC43M2gxMi4wNnYtMTguODQKCQkJCWw2Ljk5LDAuOTNsOC4wMSwxNy45MWgxMy42Nkw0MDMuMjYsMTM5LjIzeiBNMzk0LjcxLDEzMC44NmgtMTAuMjh2LTEyLjAyaDEwLjI4YzMuMjQsMCw0LjcxLDEuNTMsNC43MSw1LjkxCgkJCQlDMzk5LjQxLDEyOS41NiwzOTguMzcsMTMwLjg2LDM5NC43MSwxMzAuODYiLz4KCQkJPHBhdGggY2xhc3M9InN0MiIgZD0iTTEwNi44MSwxNDQuOTd2LTM2LjAzSDk0LjA3djM5LjZjMCw3LjY3LDUuNzMsMTAuMDgsMTIuMywxMC4wOGgyMy4xN1YxNDguNWgtMTcuOTMKCQkJCUMxMDkuMzcsMTQ4LjUsMTA2LjgxLDE0OC41NiwxMDYuODEsMTQ0Ljk3Ii8+CgkJCTxyZWN0IHg9IjEzNS40NSIgeT0iMTA4LjkzIiBjbGFzcz0ic3QyIiB3aWR0aD0iMTIuNzMiIGhlaWdodD0iNDkuNjciLz4KCQkJPHBhdGggY2xhc3M9InN0MiIgZD0iTTE5OC45OCwxNDEuMTdWMTI4LjdjMC0wLjQ0LDAuMDUtMC44MSwwLjExLTEuMWMwLjE5LTEuNiwwLjc4LTMuMiwxLjY3LTQuNjJ2LTE0LjA1aC0xMi43M3YyOS4xMQoJCQkJbC0xOS43NC0yOS4xMUgxNTUuNHY0OS42N2gxMi44MVYxMzBsMTkuODIsMjguNmgxMi43M3YtMTEuNjVjLTAuODgtMS40My0xLjQ4LTMuMDYtMS42Ny00LjcKCQkJCUMxOTkuMDMsMTQxLjk3LDE5OC45OCwxNDEuNjEsMTk4Ljk4LDE0MS4xNyIvPgoJCQk8cGF0aCBjbGFzcz0ic3QxIiBkPSJNMjM0LjY2LDEyNS41MmMtMC4xNi0wLjE4LTAuMzMtMC4zMy0wLjUxLTAuNDdjLTAuMDktMC4wNy0wLjE3LTAuMTQtMC4yNi0wLjIyCgkJCQljLTAuMDQtMC4wNC0wLjA4LTAuMDctMC4xMi0wLjFsLTEwLjc3LTYuMjJjLTAuNTctMC4zMy0xLjQxLTAuNTItMi4yOC0wLjUyYy0wLjg4LDAtMS43MSwwLjE5LTIuMjgsMC41MmwtMTAuOCw2LjIzCgkJCQljLTAuMDIsMC4wMS0wLjA1LDAuMDUtMC4wOSwwLjA5Yy0wLjA4LDAuMDctMC4xNywwLjE1LTAuMjUsMC4yMmMtMC4xNywwLjE0LTAuMzQsMC4yOS0wLjUsMC40N2wxMy45Myw3LjM2TDIzNC42NiwxMjUuNTJ6Ii8+CgkJCTxwYXRoIGNsYXNzPSJzdDEiIGQ9Ik0yMDUuNDMsMTI4LjQ0Yy0wLjAxLDAuMTEtMC4wMywwLjIzLTAuMDYsMC4zNHYxMi4zMWMwLjAzLDAuMTQsMC4wNSwwLjI0LDAuMDYsMC4zNQoJCQkJYzAuMTIsMS4zOSwxLjEyLDMuMDUsMi4yMywzLjY5bDEwLjgsNi4yM2MwLjI1LDAuMTUsMC41NiwwLjI2LDAuODksMC4zNXYtMTYuNDJsLTEzLjg0LTcuMzEKCQkJCUMyMDUuNDcsMTI4LjE0LDIwNS40NCwxMjguMjksMjA1LjQzLDEyOC40NCIvPgoJCQk8cGF0aCBjbGFzcz0ic3QyIiBkPSJNMjIzLjAyLDE1MS4zNmwxMC44LTYuMjNjMS4yMi0wLjcsMi4yOC0yLjU1LDIuMjgtMy45NVYxMjguN2MwLTAuMjMtMC4wMy0wLjQ4LTAuMDktMC43NGwtMTMuODgsNy4zM3YxNi40MgoJCQkJQzIyMi40NiwxNTEuNjIsMjIyLjc2LDE1MS41LDIyMy4wMiwxNTEuMzYiLz4KCQk8L2c+Cgk8L2c+CjwvZz4KPC9zdmc+Cg==
      mediatype: image/svg+xml
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - Storage
    - DRBD
  links:
    - name: LINBIT
      url: https://www.linbit.com/
    - name: User Guide
      url: https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#ch-openshift
  maintainers:
    - name: LINBIT
      email: sales@linbit.com
  maturity: beta
  provider:
    name: LINBIT
