# Adds namespace to all resources.
namespace: linbit-sds

namePrefix: linstor-operator-
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: linbit-sds

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: drbdio-pull-secret
          containers:
          - name: manager
            env:
              - name: PULL_SECRET
                value: drbdio-pull-secret
  target:
    kind: Deployment
    name: controller-manager
- path: default_images.yaml
  target:
    kind: ConfigMap
    name: config

images:
- name: controller
  newName: drbd.io/linstor-operator
  newTag: v2.0.1

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../piraeus-operator/config/crd
- ../../piraeus-operator/config/rbac
- ../../piraeus-operator/config/manager
- ../../piraeus-operator/config/webhook
- ../../piraeus-operator/config/certmanager

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml
- manager_webhook_patch.yaml
- webhookcainjection_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: webhook-service
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
  - fieldPaths:
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
- source:
    kind: Service
    name: webhook-service
  targets:
  - fieldPaths:
    - spec.dnsNames.0
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
  - fieldPaths:
    - spec.dnsNames.1
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: serving-cert
      version: v1
- source:
    kind: Certificate
    name: serving-cert
    fieldPath: metadata.namespace
  targets:
    - fieldPaths:
        - metadata.annotations.[cert-manager.io/inject-ca-from]
      options:
        delimiter: /
        index: 0
      select:
        kind: ValidatingWebhookConfiguration
        name: validating-webhook-configuration
- source:
    kind: Certificate
    name: serving-cert
    fieldPath: metadata.name
  targets:
    - fieldPaths:
        - metadata.annotations.[cert-manager.io/inject-ca-from]
      options:
        delimiter: /
        index: 1
      select:
        kind: ValidatingWebhookConfiguration
        name: validating-webhook-configuration
