# Adds namespace to all resources.
namespace: linbit-sds

namePrefix: linstor-operator-
labels:
  - pairs:
      app.kubernetes.io/name: linbit-sds
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: controller-manager
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller-manager
      spec:
        template:
          spec:
            imagePullSecrets:
            - name: drbdio-pull-secret
            containers:
            - name: manager
              env:
                - name: PULL_SECRET
                  value: drbdio-pull-secret
  - target:
      kind: ConfigMap
      name: config
    path: default_images.yaml

images:
  - name: controller
    newName: drbd.io/linstor-operator
    newTag: v2

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../piraeus-operator/config/crd
- ../../piraeus-operator/config/rbac
- ../../piraeus-operator/config/manager
- ../../piraeus-operator/config/webhook
- ../../piraeus-operator/config/certmanager

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml
- manager_webhook_patch.yaml
- webhookcainjection_patch.yaml

vars:
- name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert # this name should match the one in certificate.yaml
  fieldref:
    fieldpath: metadata.namespace
- name: CERTIFICATE_NAME
  objref:
    kind: Certificate
    group: cert-manager.io
    version: v1
    name: serving-cert # this name should match the one in certificate.yaml
- name: SERVICE_NAMESPACE # namespace of the service
  objref:
    kind: Service
    version: v1
    name: webhook-service
  fieldref:
    fieldpath: metadata.namespace
- name: SERVICE_NAME
  objref:
    kind: Service
    version: v1
    name: webhook-service
