# Adds namespace to all resources.
namespace: linbit-sds

namePrefix: linstor-operator-
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: linbit-sds

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: drbdio-pull-secret
          containers:
          - name: manager
            env:
              - name: PULL_SECRET
                value: drbdio-pull-secret
  target:
    kind: Deployment
    name: controller-manager
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gencert
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: drbdio-pull-secret
  target:
    kind: Deployment
    name: gencert
- patch: |
    - op: remove
      path: /data/0_piraeus_datastore_images.yaml
  target:
    kind: ConfigMap
    name: image-config
- path: manager_webhook_patch.yaml

configMapGenerator:
  - name: image-config
    files:
      - 0_linbit_sds_images.yaml
    behavior: merge

images:
- name: controller
  newName: drbd.io/linstor-operator
  newTag: v2.2.0

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../piraeus-operator/config/crd
- ../../piraeus-operator/config/rbac
- ../../piraeus-operator/config/manager
- ../../piraeus-operator/config/webhook
- ../../piraeus-operator/config/gencert

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
- source:
    kind: Service
    name: webhook-service
  targets:
    - fieldPaths:
        - spec.template.spec.containers.[name=gencert].env.[name=WEBHOOK_SERVICE_NAME].value
      select:
        kind: Deployment
        name: gencert
- source:
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
  targets:
    - fieldPaths:
        - spec.template.spec.containers.[name=gencert].env.[name=WEBHOOK_CONFIGURATION_NAME].value
      select:
        kind: Deployment
        name: gencert
    - fieldPaths:
        - rules.0.resourceNames.0
      select:
        kind: ClusterRole
        name: gencert
- source:
    fieldPath: metadata.name
    kind: ConfigMap
    name: image-config
  targets:
    - fieldPaths:
        - spec.template.spec.containers.[name=manager].env.[name=IMAGE_CONFIG_MAP_NAME].value
      select:
        kind: Deployment
        name: controller-manager
