---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linstor-operator.fullname" . }}-controller-manager
  labels:
    {{- include "linstor-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "linstor-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "linstor-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
          - --metrics-bind-address=0
          - --health-probe-bind-address=:8081
          - --namespace=$(NAMESPACE)
          - --image-config-map-name=$(IMAGE_CONFIG_MAP_NAME)
        {{- range $opt, $val := .Values.operator.options }}
          - --{{ $opt | kebabcase }}={{ $val }}
        {{- end }}
        command:
        - /manager
        env:
        - name: PULL_SECRET
          value: {{ include "linstor-operator.fullname" . }}-pull-secret
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_CONFIG_MAP_NAME
          value: {{ include "linstor-operator.fullname" . }}-image-config
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.operator.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.operator.securityContext | nindent 12}}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      imagePullSecrets:
        - name: {{ include "linstor-operator.fullname" . }}-pull-secret
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linstor-operator.serviceAccountName" . }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8}}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "linstor-operator.certifcateName" . }}
