{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "linstor-operator.fullname" . }}
  labels:
    {{- include "linstor-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "linstor-operator.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
