apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linstor-operator.fullname" . }}-pull-secret
  labels:
    {{- include "linstor-operator.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "linstor-operator.imagePullSecret" . }}
