{{ if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "linstor-operator.serviceAccountName" . }}
  labels:
    {{- include "linstor-operator.labels" . | nindent 4 }}
{{ end }}
