drbdRepoCred: drbdiocred
csi:
  pluginImage: "drbd.io/linstor-csi:v1.2.3"
operator:
  image: "drbd.io/linstor-operator:v1.10.7"
  controller:
    controllerImage: "drbd.io/linstor-controller:v1.24.2"
  satelliteSet:
    kernelModuleInjectionMode: ShippedModules
    kernelModuleInjectionImage: "drbd.io/drbd9-rhel7:v9.1.16"
    satelliteImage: "drbd.io/linstor-satellite:v1.24.2"
    monitoringImage: "drbd.io/drbd-reactor:v1.2.0"
piraeus-ha-controller:
  image:
    repository: drbd.io/linstor-k8s-ha-controller
    tag: "v1.1.4"
