drbdRepoCred: drbdiocred
csi:
  pluginImage: "drbd.io/linstor-csi:v0.17.0"
operator:
  image: "drbd.io/linstor-operator:v1.7.0-rc.5"
  controller:
    controllerImage: "drbd.io/linstor-controller:v1.17.0"
  satelliteSet:
    kernelModuleInjectionMode: ShippedModules
    kernelModuleInjectionImage: "drbd.io/drbd9-rhel7:v9.1.4"
    satelliteImage: "drbd.io/linstor-satellite:v1.17.0"
    monitoringImage: "drbd.io/drbd-reactor:v0.5.1"
haController:
  image: drbd.io/linstor-k8s-ha-controller:v0.2.1
