csi:
  image: "drbd.io/linstor-csi:v0.8.0"
operator:
  image: "drbd.io/linstor-operator:v0.3.0"
  controllerSet:
    controllerImage: "drbd.io/linstor-controller:v1.7.0"
  nodeSet:
    drbdKernelModuleInjectionMode: ShippedModules
    satelliteImage: "drbd.io/linstor-satellite:v1.7.0"
    kernelModImage: "drbd.io/drbd9-rhel7:v9.0.22-2"
