drbdRepoCred: drbdiocred
csi:
  pluginImage: "drbd.io/linstor-csi:v0.22.0"
operator:
  image: "drbd.io/linstor-operator:v1.10.1"
  controller:
    controllerImage: "drbd.io/linstor-controller:v1.20.2"
  satelliteSet:
    kernelModuleInjectionMode: ShippedModules
    kernelModuleInjectionImage: "drbd.io/drbd9-rhel7:v9.1.12"
    satelliteImage: "drbd.io/linstor-satellite:v1.20.2"
    monitoringImage: "drbd.io/drbd-reactor:v0.10.2"
haController:
  image: drbd.io/linstor-k8s-ha-controller:v0.3.0
