csi:
  pluginImage: "drbd.io/linstor-csi:v0.9.0"
operator:
  image: "drbd.io/linstor-operator:v0.5.0"
  controller:
    controllerImage: "drbd.io/linstor-controller:v1.7.1"
  satelliteSet:
    kernelModuleInjectionMode: ShippedModules
    kernelModuleInjectionImage: "drbd.io/drbd9-rhel7:v9.0.23"
    satelliteImage: "drbd.io/linstor-satellite:v1.7.1"
