csi:
  pluginImage: "drbd.io/linstor-csi:v0.8.3"
operator:
  image: "drbd.io/linstor-operator:v0.4.1"
  controllerSet:
    controllerImage: "drbd.io/linstor-controller:v1.7.1"
  nodeSet:
    drbdKernelModuleInjectionMode: ShippedModules
    satelliteImage: "drbd.io/linstor-satellite:v1.7.1"
    kernelModImage: "drbd.io/drbd9-rhel7:v9.0.23"
