drbdRepoCred: drbdiocred
csi:
  pluginImage: "drbd.io/linstor-csi:v0.9.1"
operator:
  image: "drbd.io/linstor-operator:v1.0.0"
  controller:
    controllerImage: "drbd.io/linstor-controller:v1.7.3"
  satelliteSet:
    kernelModuleInjectionMode: ShippedModules
    kernelModuleInjectionImage: "drbd.io/drbd9-rhel7:v9.0.24"
    satelliteImage: "drbd.io/linstor-satellite:v1.7.3"
