apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../piraeus-operator/config/extras/monitoring
  - ../../charts/linbit-sds
patches:
  - target:
      kind: ConfigMap
      name: piraeus-datastore-dashboard
    patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: piraeus-datastore-dashboard
      $patch: delete
  - target:
      kind: PrometheusRule
      name: piraeus-datastore
    patch: |
      - op: replace
        path: /metadata/name
        value: linbit-sds
